# Black Duck Security Action allows you to integrate Static Analysis Security Testing (SAST) and Software Composition Analysis (SCA) into your CI/CD pipelines.
# For more information about configuring your workflow,
# read our documentation at https://github.com/blackduck-inc/black-duck-security-scan

name: CI Black Duck security scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

    # set up JDK 11 in runtime environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install
        
      - name: Black Duck Polaris scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        with:
          ### ---------- POLARIS SCANNING: REQUIRED FIELDS ----------
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_name: JJ-GitHub-Demo-${{ github.event.repository.name }}
          polaris_project_name: JJ-GitHub-Demo-${{ github.event.repository.name }}
          polaris_reports_sarif_create: 'true'
          polaris_upload_sarif_report: 'true' 
          polaris_prComment_enabled: 'true'
          polaris_prComment_severities: "Critical, High, Medium, Low"
          github_token: ${{ secrets.GITHUB_TOKEN }}
